name: Create tag

# Execute this workflow after merging to *main*
on:
  push:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main

jobs:
  create-tag:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GIT_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag
        run: ./.github/workflows/script.sh

      - name: Print tags
        run: git ls-remote --tags origin
