name: Tag requirement

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  tag-require:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: |
            patch
            minor
            major
            no-tag
          add_comment: true

  semver-require:
    runs-on: ubuntu-latest
    needs: tag-require
    steps:
      - name: If semver -> check additional tag
        run: |
          labels=$(echo '${{ toJson(github.event.pull_request.labels) }}' | jq -r 'map(.name)')
          labels_size=$(echo $labels | jq '. | length')
          echo "$labels -- Number of labels: $labels_size"

          for label in $(echo $labels | jq -r 'join(" ")'); do
            echo $label
            case "$label" in
                major|minor|patch)
                  if [ $labels_size -ne 2 ]; then
                    exit 1
                  fi
                ;;
                no-tag)
                  if [ $labels_size -ne 1 ]; then
                    exit 1
                  fi
                ;;
            esac

          done
